syntax = "proto3";

package user;

service UserService {
  rpc FindById (FindByIdRequest) returns (UserResponse);
  rpc FindByEmail (FindByEmailRequest) returns (UserResponse);
  rpc UpdateKycLevel (UpdateKycLevelRequest) returns (UserResponse);
  rpc Create (CreateUserRequest) returns (UserResponse);
  rpc Validate (ValidateUserRequest) returns (UserResponse);
}

message ValidateUserRequest {
  string email = 1;
  string password = 2;
}

message FindByIdRequest {
  string id = 1;
}

message FindByEmailRequest {
  string email = 1;
}

message UpdateKycLevelRequest {
  string user_id = 1;
  int32 kyc_level = 2;
}

message CreateUserRequest {
  string email = 1;
  string password = 2;
  optional string username = 3;
  optional string referral_code = 4;
}

message UserResponse {
  string id = 1;
  string email = 2;
  optional string username = 3;
  string status = 4;
  string tier = 5;
  int32 kyc_level = 6;
  bool two_factor_enabled = 7;
  optional string password_hash = 8;
}
